#!/bin/bash

# Function to install Java on Fedora
install_java_fedora() {
    sudo dnf update
    sudo dnf install -y java-11-openjdk
}

# Function to install Screen on Fedora
install_screen_fedora() {
    sudo dnf update
    sudo dnf install -y screen
}

# Check if Java is installed
if ! command -v java &> /dev/null; then
    echo "Java is not installed. Installing..."
    install_java_fedora
fi

# Check if Screen is installed
if ! command -v screen &> /dev/null; then
    echo "Screen is not installed. Installing..."
    install_screen_fedora
fi

# Start the Minecraft server
screen -S minecraft -dm bash -c 'java -Xmx6G -jar server.jar nogui'
